# -*- coding: utf-8 -*-
"""Labwork1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4FRETHqa-oaMn813T6H7OICd569fIb2
"""

import math
def calculate_circle_area():
    r = float(input("Enter circle radius? "))
    area = math.pi * r * r
    print("Circle area =", area)
calculate_circle_area()

import math

def celsius_to_fahrenheit():
  c = float(input("Enter the temperature in Celsius? "))
  f = c * 1.8 + 32
  print(c ,"(C) =", f ,"(F) ")
celsius_to_fahrenheit()

import math

def check_prime_number():
  n = int(input("Enter a number? "))
  if n < 2:
    print ( n , "is not a prime number")
    return
    prime = True
    for i in range(2, n):
      if n % i == 0:
        prime = False
        break
    if prime:
      print ( n , "is a prime number")
    else:
      print ( n , "is not a prime number")
check_prime_number()

import math

def check_perfect_number():
  n = int(input("Enter a number?"))
  sum = 0
  for i in range(1, n):
    if n % i == 0:
      sum += i
  if sum == n:
    print ( n , "is a perfect number")
check_perfect_number()

def favorite_color():
  colors = ["Black" , "Yellow", "Blue", "Red", "White"]
  color = input("What is your favorite color? ")
  if color in colors:
    index = colors.index(color)
    print (" Yours color is at index" , index ,"in the list")
  else:
    print ("Sorry, I could not find your color")
favorite_color()

import builtins
range = builtins.range

def sequence():
    print("range1:")
    for i in range(7):
        print(i, end=" ")

    print("\nrange2:")
    for i in range(1, 11, 3):
        print(i, end=" ")

    print("\nrange3:")
    for i in range(5, 0, -1):
        print(i, end=" ")

    print("\nrange4:")
    for i in range(6, -3, -2):
        print(i, end=" ")
    print()

sequence()

def remove_dollar_sign(s):
    return s.replace("$", "")

def dollar_sign():
    s = input("Enter a string? ")
    print(remove_dollar_sign(s))

dollar_sign()

def extract_even(lst):
    result = []
    for x in lst:
        if x % 2 == 0:
            result.append(x)
    return result

def number():
    numbers = [1, 4, 5, -1, 10]
    print(extract_even(numbers))

number()

def factorial(n):
  result = 1
  for i in range (1, n+1):
    result = result * i
    return result
def number():
  n = int (input("Enter a number? "))
  print("factorial = ", factorial(n))
number()

def get_divisor(n):
  result =[]
  for i in range (1, n + 1):
    if n % i ==0 :
      result.append(i)
  return result

def number():
  n = int((input(" Enter a number: ")))
  print ("Divisor :", get_divisor(n))
number()

def distance__two__point():
  x1 = float(input("Enter x1: "))
  y1 = float(input("Enter y1: "))
  x2 = float(input("Enter x2: "))
  y2 = float(input("Enter y2: "))
  distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
  print("Distance between two points:", distance)
distance__two__point()

def print_pattern(m, n):
    for i in range(m):
        for j in range(n):
            print("*", end=" ")
        print()

def number():
    m = int(input("Enter m: "))
    n = int(input("Enter n: "))
    print_pattern(m, n)

number()